# Generated by Django 5.1 on 2024-08-23 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='تصویر محصول')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدئو محصول')),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_sale', models.BooleanField(default=False, verbose_name='فروش ویژه')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش ویژه')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
