# Generated by Django 5.1 on 2024-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.IntegerField(default=0, null=True, verbose_name='انبار'),
        ),
    ]
