# Generated by Django 5.1 on 2024-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_all',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کلی محصول'),
        ),
    ]
