# Generated by Django 5.1 on 2024-09-14 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_odered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shping_address',
            new_name='shipping_address',
        ),
    ]
